### PR TITLE
Expose the Plugin release number in the API.

### PR DESCRIPTION
**Pull request by tim-schilling**

### CODE REVIEW

**Comment by tim-schilling** [comment]
@xpazv can you take a look at this PR? I needed to expose some plugin information and don't want to merge it without an extra set of eyes.

**Comment by tim-schilling** [comment]
@andrewhancox could you take a look at this PR and potentially merge it into your changes?

**Comment by andrewhancox** [comment]
I’ve rebased it onto my change-set and pushed so it’s now all in a single PR. I’m assuming that works for you?

**Comment by tim-schilling** [comment]
Yup yup!

**Pull request closed without merging**
